- name: Hello World!
  hosts: all
  tasks:
   - name: Hello World!
     shell: echo "Hi! Tower is working."
   - template: 
     src: motd.j2
     dest: /etc/motd
     mode: 644
     owner: root
     group: root
